project_name: rtty
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
archives:
  - name_template: "{{ .ProjectName }}_{{ if index .Env \"BUILD_ID\" }}{{ .Env.BUILD_ID }}{{ else }}{{ .ShortCommit }}{{ end }}_{{ .Arch }}"
    format: zip

builds:
  - main: .
    ldflags:
      - -s -w
      - -X github.com/skanehira/rtty/cmd.Version={{.Version}}
      - -X github.com/skanehira/rtty/cmd.Revision={{.ShortCommit}}
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
